const seatsArray = [
  {
    name: 'Albany',
    margin: -5.10,
    displayMargin: -5.10,
    party: 'Labor',
  },
  {
    name: 'Armadale',
    margin: -25.17,
    displayMargin: -25.17,
    party: 'Labor',
  },
  {
    name: 'Balcatta',
    margin: -5.83,
    displayMargin: -5.83,
    party: 'Labor',
  },
  {
    name: 'Baldivis',
    margin: -7.22,
    displayMargin: -7.22,
    party: 'Labor',
  },
  {
    name: 'Bassendean',
    margin: -21.50,
    displayMargin: -21.50,
    party: 'Labor',
  },
  {
    name: 'Bateman',
    margin: 9.46,
    displayMargin: 9.46,
    party: 'Liberal',
  },
  {
    name: 'Belmont',
    margin: -11.4,
    displayMargin: -11.4,
    party: 'Labor',
  },
  {
    name: 'Bicton',
    margin: -2.93,
    displayMargin: -2.93,
    party: 'Labor',
  },
  {
    name: 'Bunbury',
    margin: -10.85,
    displayMargin: -10.85,
    party: 'Labor',
  },
  {
    name: 'Burns Beach',
    margin: -2.53,
    displayMargin: -2.53,
    party: 'Labor',
  },
  {
    name: 'Butler',
    margin: -19.45,
    displayMargin: -19.45,
    party: 'Labor',
  },
  {
    name: 'Cannington',
    margin: -18.05,
    displayMargin: -18.05,
    party: 'Labor',
  },
  {
    name: 'Carine',
    margin: 9.05,
    displayMargin: 9.05,
    party: 'Liberals',
  },
  {
    name: 'Central Wheatbelt',
    margin: 22.57,
    displayMargin: 22.57,
    party: 'Nationals',
  },
  {
    name: 'Churchlands',
    margin: 13.22,
    displayMargin: 13.22,
    party: 'Liberals',
  },
  {
    name: 'Cockburn',
    margin: -15.93,
    displayMargin: -15.93,
    party: 'Labor',
  },
  {
    name: 'Collie-Preston',
    margin: -14.71,
    displayMargin: -14.71,
    party: 'Labor',
  },
  {
    name: 'Cottesloe',
    margin: 20.1,
    displayMargin: 20.1,
    party: 'Liberal',
  },
  {
    name: 'Dawesville',
    margin: 0.69,
    displayMargin: 0.69,
    party: 'Liberal',
  },
  {
    name: 'Darling Range',
    margin: 7,
    displayMargin: 7,
    party: 'Liberals',
  },
  {
    name: 'Forrestfield',
    margin: -9.43,
    displayMargin: -9.43,
    party: 'Labor',
  },
  {
    name: 'Fremantle',
    margin: -23.05,
    displayMargin: -23.05,
    party: 'Labor',
  },
  {
    name: 'Geraldton',
    margin: 1.33,
    displayMargin: 1.33,
    party: 'Nationals',
  },
  {
    name: 'Girrawheen',
    margin: -16.71,
    displayMargin: -16.71,
    party: 'Labor',
  },
  {
    name: 'Hillarys',
    margin: 4.09,
    displayMargin: 4.09,
    party: 'Liberals',
  },
  {
    name: 'Jandakot',
    margin: -1.02,
    displayMargin: -1.02,
    party: 'Labor',
  },
  {
    name: 'Joondalup',
    margin: -0.6,
    displayMargin: -0.6,
    party: 'Labor',
  },
  {
    name: 'Kalamunda',
    margin: -2.5,
    displayMargin: -2.5,
    party: 'Labor',
  },
  {
    name: 'Kalgoorlie',
    margin: 6.18,
    displayMargin: 6.18,
    party: 'Liberals',
  },
  {
    name: 'Kimberley',
    margin: -13.01,
    displayMargin: -13.01,
    party: 'Labor',
  },
  {
    name: 'Kingsley',
    margin: -0.67,
    displayMargin: -0.67,
    party: 'Labor',
  },
  {
    name: 'Kwinana',
    margin: -18.08,
    displayMargin: -18.08,
    party: 'Labor',
  },
  {
    name: 'Mandurah',
    margin: -18,
    displayMargin: -18,
    party: 'Labor',
  },
  {
    name: 'Maylands',
    margin: -17.86,
    displayMargin: -17.86,
    party: 'Labor',
  },
  {
    name: 'Midland',
    margin: -13.05,
    displayMargin: -13.05,
    party: 'Labor',
  },
  {
    name: 'Mirrabooka',
    margin: -19.18,
    displayMargin: -19.18,
    party: 'Labor',
  },
  {
    name: 'Moore',
    margin: 13.92,
    displayMargin: 13.92,
    party: 'Nationals',
  },
  {
    name: 'Morley',
    margin: -11.43,
    displayMargin: -11.43,
    party: 'Labor',
  },
  {
    name: 'Mount Lawley',
    margin: -4.04,
    displayMargin: -4.04,
    party: 'Labor',
  },
  {
    name: 'Murray-Wellington',
    margin: -1.39,
    displayMargin: -1.39,
    party: 'Labor',
  },
  {
    name: 'Nedlands',
    margin: 8.28,
    displayMargin: 8.28,
    party: 'Liberals',
  },
  {
    name: 'North West Central',
    margin: 9.54,
    displayMargin: 9.54,
    party: 'Nationals',
  },
  {
    name: 'Perth',
    margin: -11.82,
    displayMargin: -11.82,
    party: 'Labor',
  },
  {
    name: 'Pilbara',
    margin: -2.28,
    displayMargin: -2.28,
    party: 'Labor',
  },
  {
    name: 'Riverton',
    margin: 4.36,
    displayMargin: 4.36,
    party: 'Liberals',
  },
  {
    name: 'Roe',
    margin: 14.41,
    displayMargin: 14.41,
    party: 'Nationals',
  },
  {
    name: 'Rockingham',
    margin: -23.37,
    displayMargin: -23.37,
    party: 'Labor',
  },
  {
    name: 'Scarborough',
    margin: 5.56,
    displayMargin: 5.56,
    party: 'Liberal',
  },
  {
    name: 'South Perth',
    margin: 7.15,
    displayMargin: 7.15,
    party: 'Liberals',
  },
  {
    name: 'Southern River',
    margin: -7.86,
    displayMargin: -7.86,
    party: 'Labor',
  },
  {
    name: 'Swan Hills',
    margin: -14.52,
    displayMargin: -14.52,
    party: 'Labor',
  },
  {
    name: 'Thornlie',
    margin: -15.79,
    displayMargin: -15.79,
    party: 'Labor',
  },
  {
    name: 'Vasse',
    margin: 14.69,
    displayMargin: 14.69,
    party: 'Liberals',
  },
  {
    name: 'Victoria Park',
    margin: -16.48,
    displayMargin: -16.48,
    party: 'Labor',
  },
  {
    name: 'Wanneroo',
    margin: -7.25,
    displayMargin: -7.25,
    party: 'Labor',
  },
  {
    name: 'Warnbro',
    margin: -23.72,
    displayMargin: -23.72,
    party: 'Labor',
  },
  {
    name: 'Warren-Blackwood',
    margin: 13.41,
    displayMargin: 13.41,
    party: 'Nationals',
  },
  {
    name: 'West Swan',
    margin: -17.13,
    displayMargin: -17.13,
    party: 'Labor',
  },
  {
    name: 'Willagee',
    margin: -15.49,
    displayMargin: -15.49,
    party: 'Labor',
  },
];

export default seatsArray;
